### PR TITLE
with_options helper

### PR DESCRIPTION
**Pull request by robertzk**

### CODE REVIEW

**Comment by robertzk** [comment]
Oops, nice catch!

**Comment by robertzk** [comment]
Wait, that's in devtools, not in testthat.....

**Comment by kirillseva** [comment]
I'm just saying that you could reuse devtools::with_options instead of building it yourself

**Comment by kirillseva** [comment]
Or build tests like that
https://github.com/jimhester/covr/blob/cee2e414945bd1bc0a8b69f33d3e4e6c2329bc52/tests/testthat/test-codecov.R#L2-L24

**Comment by robertzk** [comment]
I do really like his `with_something` generalization.

**Pull request closed without merging**
